### ISSUE TITLE
Main menu / UI stops working after enabling BORDER option

### ISSUE THREAD

**Issue by sromeroi** [tdlabac/MSX1_MiSTer#6] opened 2022-09-22 08:28 UTC
First of all, thanks for the great idea of implementing a standard (PAL) MSX-1, able to read ROM and CAS (and I hope in the future DSK) files.

I'm testing the core and found out that after I've opened and closed the "menu" UI a few times, it does not appear anymore.

Thanks.

**Comment by GuerreroNinja** [comment] 2022-09-22 10:16
Are you using a CRT? Because if I switch the Border option, menu only shows on HDMI.

**Comment by sromeroi** [comment] 2022-09-22 10:37
> Are you using a CRT? Because if I switch the Border option, menu only shows on HDMI.

Yes, that's it. It happened while using a CRT and I probably just switched the border option on.

I did it because the core started fine and then it shrank to a smaller portion of the screen (top-left) with a non-centered position in the CRT output, and I was looking for center controls.

Adding Jotego's framework to allow CRT centering would be very nice.

**Comment by GuerreroNinja** [comment] 2022-09-22 10:41
Yes, it happens when using a CRT, if you switch the border toggle the menu disappears. If happens also to the SVI-328 core, so seems there is some bug there in VDP?

**Comment by tdlabac** [comment] 2022-10-22 10:34
Please try the latest version. I have updated the framework. I have no way to test the behavior on CRT

**Comment by GuerreroNinja** [comment] 2022-10-22 10:56
Definitely, there is something wrong with border. On a real MSX, if you use this BASIC command:

color 15,1,2

You get white text, black background and green border. However, if I try this in the FPGA core, border color does not change at all, even with BORDER=YES in OSD menu.

This is not the original MSX behaviour, so something is happening there with border. This happens both HDMI and CRT output, does not matter, and I suspect this may be related to OSD "dissapearing" when using BORDER=YES for a second time.

So, please let me describe de steps to reproduce in CRT screen (using today's release, MSX1_20221022.rbf) to make the OSD MENU dissappear:

1. Saved default setting BORDER=YES
2. Core loads: in CRT, black top and down bars appear, Mister OSD MENU show normally. Please note that on CRT, though BORDER=YES the black bars are no border, so as stated previously, anything that change color border (like color 15,1,10) won't change black bars color. So, in fact, border is not showing, those are just black bars.
3. Open MENU, change BORDER to NO.
4. Now the CRT screen show another right black border (this may be ok as my real MSX2 show a narrow bar on the right side with the border color). Mister OSD MENU shows normally.
5. Open MENU, change BORDER to YES.
6. Now the CRT shows the full screen as color background, no top, down or right black bars. However, the MENU OSD is gone and only shows on HDMI. Please note that this is NOT border color, but background color on all screen. This is not the expected behaviour.

Workaround for now for CRT users to avoid OSD menu dissappear is saving BORDER=YES as default for core (or don't touch that option at all), then don't change that option again when executing the core. It will show black bars up and down, but core will work normally with OSD MENU showing as it should.

I hope I have explained myself.

**Comment by sromeroi** [comment] 2022-10-22 11:09
> Please try the latest version. I have updated the framework. I have no way to test the behavior on CRT

It's still happening. Let me illustrate it with a video:

[https://www.youtube.com/watch?v=mAk2JrmkWxs](https://www.youtube.com/watch?v=mAk2JrmkWxs)

@GuerreroNinja just explained that the UI works... but on the HDMI output. This is probably the reason why the keyboard is not working at the end of the video, probably the UI is open (only visible in the HDMI output) and the keystrokes are being sent to the UI instead of to the core.

EDIT: tested and confirmed. Once I activate the BORDER option, the core seems to crash because I cannot type anymore in the MSX, but it's not crashed. If I press ESC in the keyboard, then the UI (only visible in the HDMI output) closes and I can type again in the core. But I cannot open the UI anymore in the CRT.

Thanks for your time trying to fix it!

**Comment by GuerreroNinja** [comment] 2022-10-22 11:16
I have updated my comment, the problem is related to border color handling.

**Comment by GuerreroNinja** [comment] 2022-10-22 11:29
Also, the border problem also happens on SVI328 core, so this may be useful to know to pinpoint the issue.

**Comment by nonochus** [comment] 2022-10-22 12:22
Here a CRT user, just comment that the core does not hang when you activate the border, at least it does not hang for me, only that the osd does not appear until you deactivate it. For example, if I activate the border, the osd is gone, then press f12 to close the osd (although you don't see it anymore) press the f12 key again to open the osd (obviously you don't see it) press seven times (in the latest version) the cursor up and return and deactivate the border (blindly) and the osd reappears. And yes, something else happens to the border, if you use the basic color instruction, unfortunately the border color doesn't work, it always stays blue.

**Comment by tdlabac** [comment] 2022-10-22 16:07
One more question. The ColecoVision console is affected by the same bug ?
Thank you

**Comment by GuerreroNinja** [comment] 2022-10-22 23:13
> One more question. The ColecoVision console is affected by the same bug ? Thank you

I am testing the ColecoVision core on CRT and works as it should. It tested it using BRAIN STRAINERS ROM. This ROM show a blue border. If you open the OSD and set BORDER=OFF, the blue upper and lower bars turn black (the border space). You can open again the OSD and set BORDER=ON and the upper and lowers bars turn blue (which is the border color as should be). The OSD shows always on CRT, never disappear. As ColecoVision lacks a BASIC, I can't test a color 15,1,2 for example, but as the ROM tested works as expected, I suppose the border is behaving like it should. 

PD: I tested a cartridge called Facemaker, it changes border color several times, and it does OK, so I suppose ColecoVision core does well handling the border and showing OSD on CRT at all times.

PD: Beamrider flashes border with several colors when hitting an enemy or getting a life, and also do it OK.

You can also have a look at the ADAM core, though right now I don't have the BASIC cartridge to test the border.

**Comment by tdlabac** [comment] 2022-10-23 12:03
The VDP implementation is the same as in ColecoVision. The only difference I found is that MSX1 generates the image in PAL, but ColecoVision NTSC. The core SVI-328 mentioned above is also set to PAL.
I will investigate further.

**Comment by nonochus** [comment] 2022-10-23 13:12
Can be make a core with  ntsc video for testing???maybe it helps and see how works the border in ntsc.....very thanks!

**Comment by GuerreroNinja** [comment] 2022-10-23 14:30
> The VDP implementation is the same as in ColecoVision. The only difference I found is that MSX1 generates the image in PAL, but ColecoVision NTSC. The core SVI-328 mentioned above is also set to PAL. I will investigate further.

Perhaps it is something related to the TMS being implemented:

"The Texas Instruments TMS9929A is a version of the [TMS9918A] with video outputs analog YPbPr at 50Hz. MSX1 computers PAL or SECAM use generally this chip (or the TMS9129)."

So, the VDP versions are:

TMS9918A | 60Hz NTSC composite | 16k x 1bit
TMS9928A | 60Hz YPbPr |   | 16k x 1bit
TMS9929A | 50Hz YPbPr |   | 16k x 1bit
TMS9118 | 60Hz NTSC composite | 16k x 4bit
TMS9128 | 60Hz YPbPr |   | 16k x 4bit
TMS9129 | 50Hz YPbPr |   | 16k x 4bit
T6950 | 50/60Hz* composite |   | 16k x 4bit (selectable)

**Comment by GuerreroNinja** [comment] 2022-10-23 20:30
OK, forget about BORDER "bug" as I explained. I was confused because core on FIRST boot the border is black (and should be blue), so I thought I could test it using COLOR sentence, but forgot to switch to Screen 1, so the test is a non-sense in Screen 0. That does not mean the OSD Menu bug is not present, but the border bug is not as severe as I thought. Just enter OSD, disable BORDER and enable it again, and it works.

So, in a few words, border including overscan should be blue on boot and Menu OSD should not disappear on CRT screens after disabling and enabling border.

1. Core first boot, border=yes in config. See the black bars up and down:

![bug_border1](https://user-images.githubusercontent.com/32348882/197418076-b226f7a7-09d0-44fa-9c61-42637ba1b664.jpg)

2. I switch to screen 1 to see the border color change:

![bug_border2](https://user-images.githubusercontent.com/32348882/197418078-1db15636-cce6-4205-8c3f-3249c0697adf.jpg)

3. I change the border color to red, see the narrow red bars:

![bug_border3](https://user-images.githubusercontent.com/32348882/197418080-9a90ff5b-e9bb-4ca8-9076-21929217be2a.jpg)

4. I open the OSD, the menu option BORDER in on:

![bug_border4](https://user-images.githubusercontent.com/32348882/197418085-473a39b0-ed16-47fe-aa2b-b232d6aad8b3.jpg)

5. I switch the border to OFF, the red bars disappear:

![bug_border5](https://user-images.githubusercontent.com/32348882/197418093-5d7826fb-63b2-41f5-a964-0e471a532793.jpg)

6. I switch the border to "ON" again and... MAGIC, the full border is now red as it should, but we lost OSD:

![bug_border6](https://user-images.githubusercontent.com/32348882/197418094-827a813a-f98a-403c-8cdf-f681aadcccfa.jpg)

7. And if I return to screen 0, border is ok, all blue, but we lost OSD until border is switched to OFF again (if you don't have any other screen than the CRT, you can't see where is the option).

![bug_border7](https://user-images.githubusercontent.com/32348882/197418099-613ad4d1-2d68-4f4d-8d4e-f7157993c3ea.jpg)

**Comment by tdlabac** [comment] 2022-11-05 11:09
I'm trying to simulate the above problem, but despite the component video output, the OSD menu never goes away. So far I'm testing on an LCD panel with YPBPR input. For further testing I have a classic analogue TV promised. 
Can I ask for a mister.ini with the settings at which the problem manifests itself. 
Thank you.

**Comment by GuerreroNinja** [comment] 2022-11-05 11:22
Sure, here you are:

`[MiSTer]
key_menu_as_rgui=0     ; set to 1 to make the MENU key map to RGUI in Minimig (e.g. for Right Amiga)
forced_scandoubler=0   ; set to 1 to run scandoubler on VGA output always (depends on core).
ypbpr=0                ; set to 1 for YPbPr on VGA output.
composite_sync=0       ; set to 1 for composite sync on HSync signal of VGA output.
vga_scaler=0           ; set to 1 to connect VGA to scaler output.
hdmi_audio_96k=0       ; set to 1 for 96khz/16bit HDMI audio (48khz/16bit otherwise)
keyrah_mode=0x18d80002 ; VIDPID of keyrah for special code translation (0x23418037 for Arduino Micro)
vscale_mode=1          ; 0 - scale to fit the screen height.
                       ; 1 - use integer scale only.
                       ; 2 - use 0.5 steps of scale.
                       ; 3 - use 0.25 steps of scale.
vscale_border=0        ; set vertical border for TVs cutting the upper/bottom parts of screen (1-399)
;bootscreen=0          ; uncomment to disable boot screen of some cores like Minimig. 
;mouse_throttle=10     ; 1-100 mouse speed divider. Useful for very sensitive mice
rbf_hide_datecode=0    ; 1 - hides datecodes from rbf file names. Press F2 for quick temporary toggle
menu_pal=0             ; 1 - PAL mode for menu core
hdmi_limited=0         ; 1 - use limited (16..235) color range over HDMI
                       ; 2 - use limited (16..255) color range over HDMI, for VGA converters.
direct_video=0         ; 1 - enable core video timing over HDMI, use only with VGA converters.
fb_size=0              ; 0 - automatic, 1 - full size, 2 - 1/2 of resolution, 4 - 1/4 of resolution.
fb_terminal=1          ; 1 - enabled (default), 0 - disabled
osd_timeout=30         ; 5-3600 timeout (in seconds) for OSD to disappear in Menu core. 30 seconds if not set.
                       ; Background picture will get darker after double timeout
osd_rotate=0           ; Display OSD menu rotated,  0 - no rotation, 1 - rotate right (+90°), 2 - rotate left (-90°)                  

; 1 - enables the recent file loaded/mounted.
; WARNING: This option will enable write to SD card on every load/mount which may wear the SD card after many writes to the same place
;          There is also higher chance to corrupt the File System if MiSTer will be reset or powered off while writing.
recents=0

; lastcore - Autoboot the last loaded core (corename autosaved in CONFIG/lastcore.dat) first found on the SD/USB
; lastexactcore - Autoboot the last loaded exact core (corename_yyyymmdd.rbf autosaved in CONFIG/lastcore.dat) first found on the SD/USB
; corename - Autoboot first corename_*.rbf found on the SD/USB
; corename_yyyymmdd.rbf - Autoboot first corename_yyyymmdd.rbf found on the SD/USB
;bootcore=lastcore    ; uncomment to autoboot a core, as the last loaded core.

; 10-30 timeout before autoboot, comment for autoboot without timeout.
bootcore_timeout=10

; Option to load the custom font. Format is plain bitmap 8x8.
; Supported sizes of font:
;   768 bytes - chars 32-127 (only alpha + numeric)
;  1024 bytes - chars 0-127
;  1136 bytes - chars 0-141
;  up to 2048 - only chars 0-141 will be used.
; if first 32 chars are empty (for sizes 1024 bytes and more) then they are skipped.
font=font/Arcade_Aero_Fighters_(Kaneko).pf

; USER button emulation by keybaord. Usually it's reset button.
; 0 - lctrl+lalt+ralt (lctrl+lgui+rgui on keyrah)
; 1 - lctrl+lgui+rgui
; 2 - lctrl+lalt+del
; 3 - same as 0 (lctrl+lalt+ralt on keyrah)
reset_combo=0

; set to 1 for DVI mode. Audio won't be transmitted through HDMI in DVI mode.
dvi_mode=0

; 0 - 1280x720@60
; 1 - 1024x768@60
; 2 - 720x480@60
; 3 - 720x576@50
; 4 - 1280x1024@60
; 5 - 800x600@60
; 6 - 640x480@60
; 7 - 1280x720@50
; 8 - 1920x1080@60
; 9 - 1920x1080@50
;10 - 1366x768@60
;11 - 1024x600@60
;12 - 1920x1440@60
;13 - 2048x1536@60
;
; custom mode: hact,hfp,hs,hbp,vact,vfp,vs,vbp,Fpix_in_KHz
;   video_mode=1280,110,40,220,720,5,5,20,74250
video_mode=8

; set to 1-10 (seconds) to display video info on startup/change
video_info=4

; Set to 1 for automatic HDMI VSync rate adjust to match original VSync.
; Set to 2 for low latency mode (single buffer).
; This option makes video butter smooth like on original emulated system.
; Adjusting is done by changing pixel clock. Not every display supports variable pixel clock.
; For proper adjusting and to reduce possible out of range pixel clock, use 60Hz HDMI video
; modes as a base even for 50Hz systems. 
vsync_adjust=1

; If you monitor doesn't support either very low (NTSC monitors may not support PAL) or 
; very high (PAL monitors may not support NTSC) then you can set refresh_min and/or refresh_max
; parameters, so vsync_adjust won't be applied for refreshes outside specified.
; These parameters are valid only when vsync_adjust is non-zero.
refresh_min=0
refresh_max=0

; These parameters have the same format as video_mode.
; You need to supply both PAL and NTSC modes if you want vsync_adjust to switch between
; predefined modes as a base. This will reduce the range of pixel clock.
;video_mode_ntsc=0
;video_mode_pal=7

; 1-10 (seconds) to display controller's button map upon first time key press
; 0 - disable
controller_info=6

; JammaSD/J-PAC/I-PAC keys to joysticks translation
; You have to provide correct VID and PID of your input device
; Examples: Legacy J-PAC with Mini-USB or USB capable I-PAC with PS/2 connectors VID=0xD209/PID=0x0301
; USB Capable J-PAC with only PS/2 connectors VID=0x04B4/PID=0x0101
; JammaSD: VID=0x04D8/PID=0xF3AD
jamma_vid=0x04D8
jamma_pid=0xF3AD

; Disable merging input devices. Use if only player 1 works.
; Leave no_merge_pid empty to apply this to all devices with the same VID.
;no_merge_vid=0x045E
;no_merge_pid=0x028E

; Speeds in sniper/non-sniper modes of mouse emulation by joystick 
; 0 - (default) - faster move in non-sniper mode, slower move in sniper mode.
; 1 - movement speeds are swapped.
sniper_mode=0

; Uncomment following option if you don't want to see a second line for long file names in listing.
;browse_expand=0

; 0 - disable MiSTer logo in Menu core
logo=0

; Custom shared folder for core supporting this feature (currently minimig and ao486 only)
; Can be relative to core's home dir or absolute path.
; Path must exist before core start to use it, or it will fail.
; Make sure USB device is mounted before use shared folder on USB!
shared_folder=

; Custom aspect ratio
;custom_aspect_ratio_1=16:10
;custom_aspect_ratio_2=1:1

;[Menu]
;video_mode=640,8,58,78,240,1,3,18,12324
;vga_scaler=1
;vscale_mode=0
;fb_terminal=1
;osd_timeout=30

[C64]
vscale_mode=1

[AO486]
vscale_mode=3

[MSX1]
vscale_mode=3
`

**Comment by tdlabac** [comment] 2022-11-05 12:05
Thank you for setting it up. My LCD does not work with this setup, but the missing OSD menu is visible on the oscilloscope.

Border NO. Menu visible.
![image](https://user-images.githubusercontent.com/14583297/200118802-0a45fd65-3658-4b27-ae45-f7da9a39ac9f.png)

Border YES. Menu not visible.
![image](https://user-images.githubusercontent.com/14583297/200118854-09a43b70-2664-45d9-a157-fd6401884f48.png)

**Comment by GuerreroNinja** [comment] 2022-11-05 12:14
You are testing the 15Khz signal I suppose. Can you reproduce the steps I detailed above to make the OSD disappear on 15Khz?

**Comment by tdlabac** [comment] 2022-11-05 20:54
Please try. I think i managed to fix the problem. [https://github.com/tdlabac/MSX1_MiSTer/blob/border/releases/MSX1_borderTest.rbf](url)

**Comment by nonochus** [comment] 2022-11-05 21:07
working here.
The osd does not disappear when the border is activated.

the border changes color correctly on screen 1 and screen 2.

I'm not sure if it should change color as soon as it boots up or at screen 0, for me in those modes the border doesn't change color.

Thank you very much, I love this core.

**Comment by nonochus** [comment] 2022-11-05 22:24
Almost forgot, tested via RGB on a crt tv ( 15Khz signal )

**Comment by GuerreroNinja** [comment] 2022-11-06 12:19
I just tested the MSX1_borderTest.rbf and I just got a black screen both HDMI and CRT outputs. @nonochus , did you do something special to launch it? 

Edit: Never mind, it was a broken download. It works perfectly!!

Border now show as it should and OSD does not disappear. 

THANK YOU TOMAS YOU ARE THE BEST!!!!

**Comment by nonochus** [comment] 2022-11-06 15:47
What a scare you gave me! I didn't do anything special and everything worked perfect, another confirmation that it works well

The core works excellently, as a suggestion I missed an option to leave the disk drive empty, for example to prevent autoboot if you want to touch something in the basic loader and you always have the possibility to leave it empty as in real hardware .

And finally, an option to be able to choose between pal / ntsc would be nice, I know that the core is based on a philips vg8020 which is a pal computer and does not have an ntsc version, but in ntsc it gives you extra speed that is appreciated a lot, especially in games, for example, f1 spirit.

Thank you very much for the core, as a child I had a philips vg8020, it brings back very good memories.

**Comment by tdlabac** [comment] 2022-11-06 16:28
nonochus
> The core works excellently, as a suggestion I missed an option to leave the disk drive empty, for example to prevent autoboot if you want to touch something in the basic loader and you always have the possibility to leave it empty as in real hardware .

This is already possible now. Unmount the image dsk can be done using backspace

**Comment by tdlabac** [comment] 2022-11-06 17:04
Fixed in new release 221106

**Closed as completed by tdlabac** 2022-11-06 17:04 UTC
